stream {
    lua_package_path "/usr/local/openresty/lualib/?.lua;;";
    
    server {
        listen 27015;
        ssl_preread on;  # Enable SNI reading
        
        set $target_backend "";

        # Determine backend based on SNI and read prefix from stream_routes.lua
        
        proxy_pass $target_backend;
        proxy_connect_timeout 1s;
        proxy_timeout 3s;
    }
}