apiVersion: v1
kind: Namespace
metadata:
  name: fitm-cloud
  labels:
    app.kubernetes.io/name: fitm-cloud
    app.kubernetes.io/managed-by: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
