user www-data;
worker_processes auto;
worker_cpu_affinity auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 2048;
        multi_accept on;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        types_hash_max_size 2048;
        server_tokens off; # Recommended practice is to turn this off

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # SSL Settings
        ##

        ssl_protocols TLSv1.2 TLSv1.3; # Dropping SSLv3 (POODLE), TLS 1.0, 1.1
        ssl_prefer_server_ciphers off; # Don't force server cipher order.

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;

        ##
        # Gzip Settings
        ##

        gzip on;

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}

stream {
    include /etc/nginx/streams-enabled/*.conf;

    server {
        listen 7443 ssl;
        #ssl_preread on;  # Enable SNI reading

        # SSL/TLS configuration (optional, but recommended for secure connections)
        ssl_certificate /etc/letsencrypt/live/fitm.cloud/fullchain.pem;  # Path to your SSL certificate
        ssl_certificate_key /etc/letsencrypt/live/fitm.cloud/privkey.pem;  # Path to your

        proxy_socket_keepalive on;
        proxy_connect_timeout 5s;
        proxy_timeout 24h;

        proxy_pass $proxy_upstream;
        # Note: The proxy_pass directive will route traffic to the appropriate upstream based on the SNI value.
    }

    server {
        listen 8080;
        ssl_preread on;

        proxy_socket_keepalive on;
        proxy_connect_timeout 5s;
        proxy_timeout 24h;

        proxy_pass $proxy_upstream;
    }
}
