# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: kube-system # Must match where your PVCs will be, or replicate across namespaces
stringData:
  # The key from 'ceph auth get-or-create client.kubernetes'
  userID: kubernetes
  userKey: <base64-encoded-secret-key>
