---
config:
  layout: elk
---
flowchart TD
    X41[รับจากกระบวนการ 4.1]
    X1[รับจากกระบวนการ 1.0]
    D4[(D4 ข้อมูลไฟล์และสิทธิ์แชร์)]
    P421([4.2.1 รับคำขอไฟล์และข้อมูลผู้ใช้])
    P422([4.2.2 ตรวจสอบสิทธิ์การเข้าถึง])
    P423([4.2.3 ตรวจสอบข้อมูลไฟล์และโครงสร้างจัดเก็บ])
    P424([4.2.4 จัดทำข้อมูลไฟล์ที่ผ่านการตรวจสอบ])
    X43[ไปยังกระบวนการ 4.3]

    X41 -->|คำขอไฟล์ที่พร้อมตรวจสอบ| P421
    X1 -->|ข้อมูลผู้ใช้ที่ผ่านการยืนยัน| P421
    P421 -->|ข้อมูลคำขอไฟล์ที่พร้อมตรวจสอบสิทธิ์| P422
    D4 -->|ข้อมูลไฟล์และสิทธิ์แชร์| P422
    P422 -->|ข้อมูลคำขอที่ผ่านการตรวจสอบสิทธิ์| P423
    P423 -->|ข้อมูลไฟล์ที่ผ่านการตรวจสอบ| P424
    P424 -->|ข้อมูลไฟล์ที่ผ่านการตรวจสอบ| X43

    class P421,P422,P423,P424 process;
    class D4 store;
    class X41,X1,X43 ref;