---
config:
  layout: elk
---
flowchart TD
    X42[รับจากกระบวนการ 4.2]
    D4[(D4 ข้อมูลไฟล์และสิทธิ์แชร์)]
    P431([4.3.1 รับข้อมูลไฟล์ที่ผ่านการตรวจสอบ])
    P432([4.3.2 จัดทำข้อมูลเมทาดาทาและสิทธิ์แชร์])
    P433([4.3.3 บันทึกข้อมูลไฟล์และสิทธิ์แชร์])
    P434([4.3.4 จัดทำคำสั่งจัดเก็บไฟล์])
    X44[ไปยังกระบวนการ 4.4]

    X42 -->|ข้อมูลไฟล์ที่ผ่านการตรวจสอบ| P431
    P431 -->|ข้อมูลไฟล์ที่พร้อมจัดทำเมทาดาทา| P432
    P432 -->|ข้อมูลไฟล์และสิทธิ์แชร์| P433
    P433 -->|ข้อมูลไฟล์และสิทธิ์แชร์| D4
    P433 -->|ข้อมูลไฟล์ที่บันทึกแล้ว| P434
    P434 -->|ข้อมูลไฟล์และคำสั่งจัดเก็บ| X44

    class P431,P432,P433,P434 process;
    class D4 store;
    class X42,X44 ref;