---
config:
  layout: elk
---
flowchart TD
    E2[อาจารย์ / ผู้ดูแลระบบ]
    D2[(D2 ข้อมูลวิชาการและคำร้อง)]
    P231([2.3.1 รับข้อมูลพิจารณาคำร้อง])
    P232([2.3.2 ตรวจสอบคำร้องรอพิจารณา])
    P233([2.3.3 ตัดสินผลการพิจารณา])
    P234([2.3.4 บันทึกผลการอนุมัติและประวัติคำร้อง])
    X3[ไปยังกระบวนการ 3.0]

    E2 -->|ข้อมูลอนุมัติคำร้อง| P231
    P231 -->|ข้อมูลพิจารณาคำร้อง| P232
    D2 -->|ข้อมูลคำร้องรอพิจารณา| P232
    P232 -->|ข้อมูลคำร้องที่ตรวจสอบแล้ว| P233
    P233 -->|ผลการพิจารณาคำร้อง| P234
    P234 -->|ผลการอนุมัติและประวัติคำร้อง| D2
    P234 -->|คำร้องที่อนุมัติแล้ว| X3

    class P231,P232,P233,P234 process;
    class D2 store;
    class E2 entity;
    class X3 ref;