---
config:
  layout: elk
---
flowchart TD
    D2[(D2 ข้อมูลวิชาการและคำร้อง)]
    E1[นักศึกษา]
    E2[อาจารย์ / ผู้ดูแลระบบ]
    P241([2.4.1 รับข้อมูลคำร้องและข้อมูลวิชาการ])
    P242([2.4.2 สรุปสถานะคำร้อง])
    P243([2.4.3 จัดทำข้อมูลแดชบอร์ดและรายการคำร้อง])
    P244([2.4.4 ส่งผลลัพธ์คำร้องให้ผู้ใช้งาน])

    D2 -->|สถานะคำร้องและข้อมูลวิชาการ| P241
    P241 -->|ข้อมูลคำร้องที่พร้อมสรุปผล| P242
    P242 -->|ข้อมูลสถานะคำร้อง| P243
    P243 -->|ผลลัพธ์คำร้องและข้อมูลแดชบอร์ด| P244
    P244 -->|สถานะคำร้อง| E1
    P244 -->|รายการคำร้องและข้อมูลวิชาการ| E2

    class E1,E2 entity;
    class P241,P242,P243,P244 process;
    class D2 store;