---
config:
  layout: elk
---
flowchart TD
    X52[รับจากกระบวนการ 5.2]
    E4[Proxmox VE Cluster]
    P531([5.3.1 ส่งคำสั่งไปยัง Proxmox VE])
    P532([5.3.2 ติดตามสถานะการทำงาน])
    P533([5.3.3 รับผลการดำเนินงานเครื่อง])
    X54[ไปยังกระบวนการ 5.4]

    X52 -->|คำสั่งจัดสรรและควบคุมเครื่อง| P531
    P531 -->|คำสั่งจัดสรรและควบคุมเครื่อง| E4
    E4 -->|สถานะและผลการดำเนินงานเครื่อง| P532
    P532 -->|สถานะการทำงานเครื่อง| P533
    P533 -->|ผลการดำเนินงานเครื่อง| X54

    class P531,P532,P533 process;
    class E4 entity;
    class X52,X54 ref;