---
config:
  layout: elk
---
flowchart TD
    X13[รับจากกระบวนการ 1.3]
    E1[นักศึกษา]
    E2[อาจารย์ / ผู้ดูแลระบบ]
    X2[ไปยังกระบวนการ 2.0]
    X3[ไปยังกระบวนการ 3.0]
    X4[ไปยังกระบวนการ 4.0]
    P141([1.4.1 รับข้อมูลผู้ใช้ที่ผ่านการยืนยัน])
    P142([1.4.2 จัดทำผลการยืนยันตัวตน])
    P143([1.4.3 ส่งผลให้ผู้ใช้งาน])
    P144([1.4.4 กระจายข้อมูลผู้ใช้ไปยังกระบวนการที่เกี่ยวข้อง])

    X13 -->|ข้อมูลผู้ใช้ที่ผ่านการยืนยัน| P141
    P141 -->|ข้อมูลผู้ใช้ที่พร้อมจัดทำผลลัพธ์| P142
    P142 -->|ผลการยืนยันตัวตน| P143
    P142 -->|ข้อมูลผู้ใช้ที่ผ่านการยืนยัน| P144
    P143 -->|ผลการยืนยันตัวตน| E1
    P143 -->|ผลการยืนยันตัวตน| E2
    P144 -->|ข้อมูลผู้ใช้ที่ผ่านการยืนยัน| X2
    P144 -->|ข้อมูลผู้ใช้ที่ผ่านการยืนยัน| X3
    P144 -->|ข้อมูลผู้ใช้ที่ผ่านการยืนยัน| X4

    class E1,E2 entity;
    class P141,P142,P143,P144 process;
    class X13,X2,X3,X4 ref;