---
config:
  layout: elk
---
flowchart TD
    X43[รับจากกระบวนการ 4.3]
    E5[Object Storage]
    E2[อาจารย์ / ผู้ดูแลระบบ]
    P441([4.4.1 รับข้อมูลไฟล์และคำสั่งจัดเก็บ])
    P442([4.4.2 ส่งคำสั่งจัดเก็บไปยัง Object Storage])
    P443([4.4.3 รับผลการจัดเก็บและข้อมูลไฟล์])
    P444([4.4.4 สร้างลิงก์และผลลัพธ์การเข้าถึงไฟล์])

    X43 -->|ข้อมูลไฟล์และคำสั่งจัดเก็บ| P441
    P441 -->|คำสั่งจัดเก็บที่พร้อมส่ง| P442
    P442 -->|ข้อมูลไฟล์และคำสั่งจัดเก็บ| E5
    E5 -->|ผลการจัดเก็บและข้อมูลไฟล์| P443
    P443 -->|ข้อมูลไฟล์ที่จัดเก็บแล้ว| P444
    P444 -->|ข้อมูลการเชื่อมต่อและลิงก์ไฟล์| E2

    class E2,E5 entity;
    class P441,P442,P443,P444 process;
    class X43 ref;