---
config:
  layout: elk
---
flowchart TD
    X51[รับจากกระบวนการ 5.1]
    D3[(D3 ข้อมูลเครื่องเสมือน)]
    P521([5.2.1 รับงานที่พร้อมประมวลผล])
    P522([5.2.2 โหลดข้อมูลเครื่องเสมือน])
    P523([5.2.3 โหลดข้อมูลแม่แบบและพารามิเตอร์])
    P524([5.2.4 จัดทำคำสั่งจัดสรรและควบคุมเครื่อง])
    X53[ไปยังกระบวนการ 5.3]

    X51 -->|งานที่พร้อมประมวลผล| P521
    P521 -->|ข้อมูลงานที่พร้อมโหลดข้อมูลเครื่อง| P522
    D3 -->|ข้อมูลเครื่องเสมือนและแม่แบบ| P522
    P522 -->|ข้อมูลเครื่องและแม่แบบ| P523
    P523 -->|ข้อมูลที่พร้อมสร้างคำสั่ง| P524
    P524 -->|คำสั่งจัดสรรและควบคุมเครื่อง| X53

    class P521,P522,P523,P524 process;
    class D3 store;
    class X51,X53 ref;