---
config:
  layout: elk
---
flowchart TD
    E1[นักศึกษา]
    E2[อาจารย์ / ผู้ดูแลระบบ]
    P111([1.1.1 รับข้อมูลเข้าสู่ระบบ])
    P112([1.1.2 ตรวจสอบความครบถ้วนของข้อมูล])
    P113([1.1.3 ระบุประเภทผู้ใช้และช่องทางเข้าสู่ระบบ])
    X12[ไปยังกระบวนการ 1.2]

    E1 -->|ข้อมูลเข้าสู่ระบบ| P111
    E2 -->|ข้อมูลเข้าสู่ระบบ| P111
    P111 -->|ข้อมูลเข้าสู่ระบบที่รับแล้ว| P112
    P112 -->|ข้อมูลเข้าสู่ระบบที่ตรวจสอบแล้ว| P113
    P113 -->|ข้อมูลผู้ใช้สำหรับยืนยันตัวตน| X12

    class E1,E2 entity;
    class P111,P112,P113 process;
    class X12 ref;