---
config:
  layout: elk
---
flowchart TD
    E2[อาจารย์ / ผู้ดูแลระบบ]
    P411([4.1.1 รับคำขอจัดการไฟล์])
    P412([4.1.2 ระบุประเภทการดำเนินการกับไฟล์])
    P413([4.1.3 จัดเตรียมคำขอตรวจสอบ])
    X42[ไปยังกระบวนการ 4.2]

    E2 -->|คำขอจัดการไฟล์| P411
    P411 -->|คำขอไฟล์ที่รับแล้ว| P412
    P412 -->|คำขอไฟล์ที่จัดประเภทแล้ว| P413
    P413 -->|คำขอไฟล์ที่พร้อมตรวจสอบ| X42

    class E2 entity;
    class P411,P412,P413 process;
    class X42 ref;