---
config:
  layout: elk
---
flowchart TD
    D5[(D5 คิวงานเครื่องเสมือน)]
    P511([5.1.1 รับงานจากคิว])
    P512([5.1.2 ตรวจสอบสถานะและความพร้อมของงาน])
    P513([5.1.3 จองงานสำหรับการประมวลผล])
    X52[ไปยังกระบวนการ 5.2]

    D5 -->|งานจัดสรรและควบคุมเครื่อง| P511
    P511 -->|งานที่ดึงจากคิวแล้ว| P512
    P512 -->|งานที่พร้อมประมวลผล| P513
    P513 -->|งานที่พร้อมประมวลผล| X52

    class P511,P512,P513 process;
    class D5 store;
    class X52 ref;